Stable with tests
jlab/algorithm_vxdetector pull request #21
Opened 2022-07-28 14:22 UTC by JGroos-16

2022-08-16 09:43 UTC, sjanssen2 requested changes
Sieht bis auf Kleinigkeiten sehr gut aus!

Hier noch ein paar Fragen zu bestimmten Dateien:
ist es notwendig diese leere Datei im Repo zu haben? `vxdetector/tests/test_data/Indexed_bt2/BED.bed`

der Ordner scheint mit nicht gut für diese Datei, denn es sollte nichts mit den ipynb_checkpoints zu tun haben: `Indexed_bt2/.ipynb_checkpoints/annoted_ref-checkpoint.bed`

hier sind drei log Dateien. Brauchen wir die im Repo?
vxdetector/tests/test_data/paired/bed.log
vxdetector/tests/test_data/paired/bowtie2.log
vxdetector/tests/test_data/unpaired/bowtie2.log

2022-08-16 09:43 UTC, sjanssen2 commented on README.md
> +    Module: pandas
das Python Modul würde ich hier weglassen und "nur" im environment.yml erwähnen, die externen Programme können ruhig hier stehen bleiben

2022-08-16 09:43 UTC, sjanssen2 commented on environment.yml
> +  - samtools==1.11
ist es wirklich notwendig die Version von samtools so stark einzuschränken? Wäre ein >=1.11 auch möglich?

2022-08-16 09:43 UTC, sjanssen2 commented on setup.py
> +    'Programming Language :: Python :: 3.4',
wir haben doch bestimmt neuere Python Versionen verwendet, oder?

2022-08-16 09:43 UTC, sjanssen2 commented on Indexed_bt2/code_for_reference/create_annoted_ref.py
> +def write(seq_chrom, annoted_ref, region):
`write` ist ein Funktionsname der bestimmt in irgendeinem Konflikt zu anderen Funktionen steht. Vielleicht besser ändern?

2022-08-16 09:43 UTC, sjanssen2 commented on Indexed_bt2/code_for_reference/create_annoted_ref.py
> +def write(seq_chrom, annoted_ref, region):
bitte je ein kurzer Satz zur Dokumentation was welcher Parameter ist, z.B. annotated_ref : filepath to ...

2022-08-16 09:43 UTC, sjanssen2 commented on vxdetector/VXdetector.py
> +sys.path.append('$CONDA/lib/python3.9/site-packages')
sieht nach einem fiesen Hack aus. Wozu brauchen wir das?

2022-08-16 09:43 UTC, sjanssen2 commented on vxdetector/VXdetector.py
> +import vxdetector.files_manager as files_manager  # noqa: E402
was macht das `noqa: E402`?

2022-08-23 08:05 UTC, JGroos-16 commented on vxdetector/VXdetector.py
> +import vxdetector.files_manager as files_manager  # noqa: E402
Da ich davor ueber sys.path einen Pfad, wo es nach modulen zum importieren suchen soll, hinzufuege, meckert flake8, dass die imports nicht ganz oben stehen. Das '# noqa: E402' fuehrt dazu, dass flake 8 bei diesem (und nur diesem) Fehler nicht meckert.

2022-08-23 10:26 UTC, JGroos-16 commented
Die drei Log Dateien werden zum testen von Output_counter benoetigt

2022-08-23 10:52 UTC, JGroos-16 commented
Die leere BED.bed Datei wird dafuer benoetigt, um zu testen, was Output_counter macht, wenn die bowtie2.log fehlt aber eine BED.bed da ist. Der Inhalt der BED ist dabei egal, ich brauchte nur einen Ordner in der keine bowtie2.log ist, aber keine BED.bed.
Deswegen habe ich einfach eine leere Datei da erstellt.

2022-08-23 19:46 UTC, sjanssen2 commented
> Die drei Log Dateien werden zum testen von Output_counter benoetigt

OK, dann bleiben sie drin


> Die leere BED.bed Datei wird dafuer benoetigt, um zu testen, was Output_counter macht, wenn die bowtie2.log fehlt aber eine BED.bed da ist. Der Inhalt der BED ist dabei egal, ich brauchte nur einen Ordner in der keine bowtie2.log ist, aber eine BED.bed.
> Deswegen habe ich einfach eine leere Datei da erstellt.

klingt korrekt. Dann bitte so lassen.

2022-08-25 08:08 UTC, closed without merging